core_administradores:
    resource: "@AdminBundle/Controller/UsuariosController.php"
    type:     annotation

core_usuarios:
    resource: "@AdminBundle/Controller/UsuariosController.php"
    type:     annotation

core_fotos:
    resource: "@AdminBundle/Controller/FotosController.php"
    type:     annotation

core_banners:
    resource: "@AdminBundle/Controller/BannersController.php"
    type:     annotation

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

logoutadmin:
    path: /admin/logout

logout:
    path: /logout

frontend:
    resource: "@FrontendBundle/Controller/"
    type:     annotation
    prefix:   /

core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /core